git clone git@github.com:5cript/wretched-css.git
git clone git@github.com:5cript/mplex.git
git clone git@github.com:5cript/SimpleJSON.git
git clone git@github.com:5cript/SimpleUtil.git
git clone git@github.com:5cript/twisted-spirit.git
git clone git@github.com:5cript/wiki-client.git
git clone git@github.com:5cript/wiki-editor.git
git clone git@github.com:5cript/wiki-markup.git
git clone git@github.com:5cript/wiki-meta.git
git clone git@github.com:5cript/wiki-editor-vcl.git
git clone git@github.com:5cript/dll.git
git clone git@github.com:5cript/wiki-vcl-css.git